[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "weavelang-pipeline"
version = "0.1.0"
authors = [
  { name="Bill Branch", email="author@example.com" },
]
description = "The Python-based data generation pipeline for the WeaveLang project."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]