from typing import Any, Dict

from .base import SpaCyStage, logger
from .. import helper # Import the helper

class LemmatizeInverseDiglotMap(SpaCyStage):
    """Stage 10: Processes the `inverse_diglot_map` generated by Stage 9."""
    def __init__(self, book_stem: str, cli_args: Any, common_resources: Dict[str, Any]):
        super().__init__(book_stem, cli_args, common_resources, stage_number=10, stage_name="LemmatizeInverseDiglotMap")

    def _process_data(self, data: Dict[str, Any]) -> Dict[str, Any]:
        spacy_es = self.resources.get("spacy_models", {}).get("es")
        if not spacy_es:
            logger.critical("      -> CRITICAL: Spanish SpaCy model not found.")
            return data

        for block in data.get("content_blocks", []):
            if block.get("block_type") == "sentence":
                for seg in block.get("adv_spanish_segments", []):
                    # --- START MODIFIED LOGIC ---
                    # `inverse_diglot_map` is now a list of dictionary entries.
                    # We iterate through it and update each entry in place.
                    map_entries = seg.get("inverse_diglot_map", [])
                    for entry in map_entries:
                        spanish_word = entry.get("spanish_word", "")
                        if spanish_word:
                            # Use SpaCy to process the Spanish word
                            doc = spacy_es(spanish_word)
                            # Find the first non-punctuation token to get the lemma
                            main_token = next((t for t in doc if not t.is_punct), None)
                            if main_token:
                                # Use our centralized normalizer for consistency
                                normalized_lemma = helper.normalize_spanish_lemma(main_token.lemma_)
                                # Update the 'spanish_lemma' field in the entry
                                entry["spanish_lemma"] = normalized_lemma
                            else:
                                # If no token found, fall back to a normalized version of the word itself
                                entry["spanish_lemma"] = helper.normalize_spanish_lemma(spanish_word)
                    # --- END MODIFIED LOGIC ---
            
            block.setdefault("llm_call_status", {})[f"stage{self.stage_number}"] = "COMPLETED_SPACY"
        
        return data