from typing import Any, Dict

from .base import SpaCyStage, logger
from .. import helper # Import the helper

class LemmatizeInverseDiglotMap(SpaCyStage):
    """Stage 10: Processes the `inverse_diglot_map` generated by Stage 9."""
    def __init__(self, book_stem: str, cli_args: Any, common_resources: Dict[str, Any]):
        super().__init__(book_stem, cli_args, common_resources, stage_number=10, stage_name="LemmatizeInverseDiglotMap")

    def _process_data(self, data: Dict[str, Any]) -> Dict[str, Any]:
        spacy_es = self.resources.get("spacy_models", {}).get("es")
        if not spacy_es:
            logger.critical("      -> CRITICAL: Spanish SpaCy model not found.")
            return data

        for block in data.get("content_blocks", []):
            if block.get("block_type") == "sentence":
                for seg in block.get("adv_spanish_segments", []):
                    token_based_map = seg.get("inverse_diglot_map", {})
                    lemmatized_map = {}
                    if token_based_map:
                        for token_str, eng_sub in token_based_map.items():
                            # Normalize the lemma produced by SpaCy
                            doc = spacy_es(token_str)
                            main_token = next((t for t in doc if not t.is_punct), None)
                            if main_token:
                                lemma = helper.normalize_spanish_lemma(main_token.lemma_)
                                if lemma: # Only add if the lemma is valid
                                    lemmatized_map[lemma] = eng_sub
                    seg["inverse_diglot_map"] = lemmatized_map
            block.setdefault("llm_call_status", {})[f"stage{self.stage_number}"] = "COMPLETED_SPACY"
        return data